export const songs = [
  // 1950s
  { title: 'Rock Around the Clock', artist: 'Bill Haley & His Comets', year: 1954, previewUrl: '' },
  { title: "That's All Right", artist: 'Elvis Presley', year: 1954, previewUrl: '' },
  { title: 'Tutti Frutti', artist: 'Little Richard', year: 1955, previewUrl: '' },
  { title: 'Maybellene', artist: 'Chuck Berry', year: 1955, previewUrl: '' },
  { title: 'Blue Suede Shoes', artist: 'Carl Perkins', year: 1956, previewUrl: '' },
  { title: 'Heartbreak Hotel', artist: 'Elvis Presley', year: 1956, previewUrl: '' },
  { title: 'Long Tall Sally', artist: 'Little Richard', year: 1956, previewUrl: '' },
  { title: 'Great Balls of Fire', artist: 'Jerry Lee Lewis', year: 1957, previewUrl: '' },
  { title: "That'll Be the Day", artist: 'The Crickets', year: 1957, previewUrl: '' },
  { title: 'Jailhouse Rock', artist: 'Elvis Presley', year: 1957, previewUrl: '' },
  { title: 'Wake Up Little Susie', artist: 'The Everly Brothers', year: 1957, previewUrl: '' },
  { title: 'Johnny B. Goode', artist: 'Chuck Berry', year: 1958, previewUrl: '' },
  { title: 'At the Hop', artist: 'Danny & The Juniors', year: 1957, previewUrl: '' },
  { title: 'La Bamba', artist: 'Ritchie Valens', year: 1958, previewUrl: '' },
  { title: 'Summertime Blues', artist: 'Eddie Cochran', year: 1958, previewUrl: '' },
  { title: 'What a Wonderful World', artist: 'Sam Cooke', year: 1959, previewUrl: '' },
  { title: 'Mack the Knife', artist: 'Bobby Darin', year: 1959, previewUrl: '' },
  { title: 'Shout', artist: 'The Isley Brothers', year: 1959, previewUrl: '' },

  // 1960s
  { title: 'Cathy\'s Clown', artist: 'The Everly Brothers', year: 1960, previewUrl: '' },
  { title: 'Stand By Me', artist: 'Ben E. King', year: 1961, previewUrl: '' },
  { title: 'The Twist', artist: 'Chubby Checker', year: 1960, previewUrl: '' },
  { title: 'Runaway', artist: 'Del Shannon', year: 1961, previewUrl: '' },
  { title: 'The Loco-Motion', artist: 'Little Eva', year: 1962, previewUrl: '' },
  { title: 'Surfin\' U.S.A.', artist: 'The Beach Boys', year: 1963, previewUrl: '' },
  { title: 'Be My Baby', artist: 'The Ronettes', year: 1963, previewUrl: '' },
  { title: 'She Loves You', artist: 'The Beatles', year: 1963, previewUrl: '' },
  { title: 'I Want to Hold Your Hand', artist: 'The Beatles', year: 1963, previewUrl: '' },
  { title: 'My Girl', artist: 'The Temptations', year: 1964, previewUrl: '' },
  { title: 'House of the Rising Sun', artist: 'The Animals', year: 1964, previewUrl: '' },
  { title: 'A Hard Day\'s Night', artist: 'The Beatles', year: 1964, previewUrl: '' },
  { title: 'You Really Got Me', artist: 'The Kinks', year: 1964, previewUrl: '' },
  { title: '(I Can\'t Get No) Satisfaction', artist: 'The Rolling Stones', year: 1965, previewUrl: '' },
  { title: 'Yesterday', artist: 'The Beatles', year: 1965, previewUrl: '' },
  { title: 'Like a Rolling Stone', artist: 'Bob Dylan', year: 1965, previewUrl: '' },
  { title: 'My Generation', artist: 'The Who', year: 1965, previewUrl: '' },
  { title: 'The Sound of Silence', artist: 'Simon & Garfunkel', year: 1965, previewUrl: '' },
  { title: 'California Dreamin\'', artist: 'The Mamas & The Papas', year: 1965, previewUrl: '' },
  { title: 'Good Vibrations', artist: 'The Beach Boys', year: 1966, previewUrl: '' },
  { title: 'Paint It Black', artist: 'The Rolling Stones', year: 1966, previewUrl: '' },
  { title: 'These Boots Are Made for Walkin\'', artist: 'Nancy Sinatra', year: 1966, previewUrl: '' },
  { title: 'Wouldn\'t It Be Nice', artist: 'The Beach Boys', year: 1966, previewUrl: '' },
  { title: 'Respect', artist: 'Aretha Franklin', year: 1967, previewUrl: '' },
  { title: 'Light My Fire', artist: 'The Doors', year: 1967, previewUrl: '' },
  { title: 'A Whiter Shade of Pale', artist: 'Procol Harum', year: 1967, previewUrl: '' },
  { title: 'Brown Eyed Girl', artist: 'Van Morrison', year: 1967, previewUrl: '' },
  { title: 'What a Wonderful World', artist: 'Louis Armstrong', year: 1967, previewUrl: '' },
  { title: 'Somebody to Love', artist: 'Jefferson Airplane', year: 1967, previewUrl: '' },
  { title: 'Purple Haze', artist: 'Jimi Hendrix', year: 1967, previewUrl: '' },
  { title: 'All You Need Is Love', artist: 'The Beatles', year: 1967, previewUrl: '' },
  { title: 'Hey Jude', artist: 'The Beatles', year: 1968, previewUrl: '' },
  { title: 'Born to Be Wild', artist: 'Steppenwolf', year: 1968, previewUrl: '' },
  { title: '(Sittin\' On) The Dock of the Bay', artist: 'Otis Redding', year: 1968, previewUrl: '' },
  { title: 'Mrs. Robinson', artist: 'Simon & Garfunkel', year: 1968, previewUrl: '' },
  { title: 'Sympathy for the Devil', artist: 'The Rolling Stones', year: 1968, previewUrl: '' },
  { title: 'Here Comes the Sun', artist: 'The Beatles', year: 1969, previewUrl: '' },
  { title: 'Honky Tonk Women', artist: 'The Rolling Stones', year: 1969, previewUrl: '' },
  { title: 'Suspicious Minds', artist: 'Elvis Presley', year: 1969, previewUrl: '' },
  { title: 'Proud Mary', artist: 'Creedence Clearwater Revival', year: 1969, previewUrl: '' },
  { title: 'Bad Moon Rising', artist: 'Creedence Clearwater Revival', year: 1969, previewUrl: '' },
  { title: 'Come Together', artist: 'The Beatles', year: 1969, previewUrl: '' },

  // 1970s
  { title: 'Let It Be', artist: 'The Beatles', year: 1970, previewUrl: '' },
  { title: 'Bridge Over Troubled Water', artist: 'Simon & Garfunkel', year: 1970, previewUrl: '' },
  { title: 'American Woman', artist: 'The Guess Who', year: 1970, previewUrl: '' },
  { title: 'Lola', artist: 'The Kinks', year: 1970, previewUrl: '' },
  { title: 'Your Song', artist: 'Elton John', year: 1970, previewUrl: '' },
  { title: 'War', artist: 'Edwin Starr', year: 1970, previewUrl: '' },
  { title: 'Ain\'t No Sunshine', artist: 'Bill Withers', year: 1971, previewUrl: '' },
  { title: 'Imagine', artist: 'John Lennon', year: 1971, previewUrl: '' },
  { title: 'American Pie', artist: 'Don McLean', year: 1971, previewUrl: '' },
  { title: 'What\'s Going On', artist: 'Marvin Gaye', year: 1971, previewUrl: '' },
  { title: 'Stairway to Heaven', artist: 'Led Zeppelin', year: 1971, previewUrl: '' },
  { title: 'Maggie May', artist: 'Rod Stewart', year: 1971, previewUrl: '' },
  { title: 'Brown Sugar', artist: 'The Rolling Stones', year: 1971, previewUrl: '' },
  { title: 'Superstition', artist: 'Stevie Wonder', year: 1972, previewUrl: '' },
  { title: 'Lean on Me', artist: 'Bill Withers', year: 1972, previewUrl: '' },
  { title: 'Tiny Dancer', artist: 'Elton John', year: 1972, previewUrl: '' },
  { title: 'Heart of Gold', artist: 'Neil Young', year: 1972, previewUrl: '' },
  { title: 'American Pie', artist: 'Don McLean', year: 1972, previewUrl: '' },
  { title: 'Killing Me Softly With His Song', artist: 'Roberta Flack', year: 1973, previewUrl: '' },
  { title: 'Tie a Yellow Ribbon Round the Ole Oak Tree', artist: 'Tony Orlando & Dawn', year: 1973, previewUrl: '' },
  { title: 'Dream On', artist: 'Aerosmith', year: 1973, previewUrl: '' },
  { title: 'Free Bird', artist: 'Lynyrd Skynyrd', year: 1973, previewUrl: '' },
  { title: 'Waterloo', artist: 'ABBA', year: 1974, previewUrl: '' },
  { title: 'Sweet Home Alabama', artist: 'Lynyrd Skynyrd', year: 1974, previewUrl: '' },
  { title: 'Take Me Home, Country Roads', artist: 'John Denver', year: 1971, previewUrl: '' },
  { title: 'Rock the Boat', artist: 'The Hues Corporation', year: 1974, previewUrl: '' },
  { title: 'Bohemian Rhapsody', artist: 'Queen', year: 1975, previewUrl: '' },
  { title: 'Love Will Keep Us Together', artist: 'Captain & Tennille', year: 1975, previewUrl: '' },
  { title: 'Lyin\' Eyes', artist: 'Eagles', year: 1975, previewUrl: '' },
  { title: 'Born to Run', artist: 'Bruce Springsteen', year: 1975, previewUrl: '' },
  { title: 'Dancing Queen', artist: 'ABBA', year: 1976, previewUrl: '' },
  { title: 'Go Your Own Way', artist: 'Fleetwood Mac', year: 1977, previewUrl: '' },
  { title: 'Dreams', artist: 'Fleetwood Mac', year: 1977, previewUrl: '' },
  { title: 'Hotel California', artist: 'Eagles', year: 1977, previewUrl: '' },
  { title: 'Stayin\' Alive', artist: 'Bee Gees', year: 1977, previewUrl: '' },
  { title: 'Night Fever', artist: 'Bee Gees', year: 1977, previewUrl: '' },
  { title: 'God Save the Queen', artist: 'Sex Pistols', year: 1977, previewUrl: '' },
  { title: 'Heroes', artist: 'David Bowie', year: 1977, previewUrl: '' },
  { title: 'I Will Survive', artist: 'Gloria Gaynor', year: 1978, previewUrl: '' },
  { title: 'Le Freak', artist: 'Chic', year: 1978, previewUrl: '' },
  { title: 'YMCA', artist: 'Village People', year: 1978, previewUrl: '' },
  { title: 'Roxanne', artist: 'The Police', year: 1978, previewUrl: '' },
  { title: 'Hot Stuff', artist: 'Donna Summer', year: 1979, previewUrl: '' },
  { title: 'My Sharona', artist: 'The Knack', year: 1979, previewUrl: '' },
  { title: 'Another Brick in the Wall, Pt. 2', artist: 'Pink Floyd', year: 1979, previewUrl: '' },
  { title: 'Video Killed the Radio Star', artist: 'The Buggles', year: 1979, previewUrl: '' },
  { title: 'Message in a Bottle', artist: 'The Police', year: 1979, previewUrl: '' },
  { title: 'Good Times', artist: 'Chic', year: 1979, previewUrl: '' },
  { title: 'Heart of Glass', artist: 'Blondie', year: 1979, previewUrl: '' },
  { title: 'Rapper\'s Delight', artist: 'The Sugarhill Gang', year: 1979, previewUrl: '' },

  // 1980s
  { title: 'Call Me', artist: 'Blondie', year: 1980, previewUrl: '' },
  { title: 'Another One Bites the Dust', artist: 'Queen', year: 1980, previewUrl: '' },
  { title: 'Funkytown', artist: 'Lipps Inc.', year: 1980, previewUrl: '' },
  { title: 'Rock with You', artist: 'Michael Jackson', year: 1979, previewUrl: '' },
  { title: 'Upside Down', artist: 'Diana Ross', year: 1980, previewUrl: '' },
  { title: 'Don\'t Stop Believin\'', artist: 'Journey', year: 1981, previewUrl: '' },
  { title: 'Bette Davis Eyes', artist: 'Kim Carnes', year: 1981, previewUrl: '' },
  { title: 'Tainted Love', artist: 'Soft Cell', year: 1981, previewUrl: '' },
  { title: 'Start Me Up', artist: 'The Rolling Stones', year: 1981, previewUrl: '' },
  { title: 'Under Pressure', artist: 'Queen & David Bowie', year: 1981, previewUrl: '' },
  { title: 'Super Freak', artist: 'Rick James', year: 1981, previewUrl: '' },
  { title: 'Eye of the Tiger', artist: 'Survivor', year: 1982, previewUrl: '' },
  { title: 'Billie Jean', artist: 'Michael Jackson', year: 1982, previewUrl: '' },
  { title: 'Beat It', artist: 'Michael Jackson', year: 1983, previewUrl: '' },
  { title: 'Thriller', artist: 'Michael Jackson', year: 1982, previewUrl: '' },
  { title: 'Africa', artist: 'Toto', year: 1982, previewUrl: '' },
  { title: 'Tainted Love', artist: 'Soft Cell', year: 1982, previewUrl: '' },
  { title: 'Every Breath You Take', artist: 'The Police', year: 1983, previewUrl: '' },
  { title: 'Girls Just Want to Have Fun', artist: 'Cyndi Lauper', year: 1983, previewUrl: '' },
  { title: 'Karma Chameleon', artist: 'Culture Club', year: 1983, previewUrl: '' },
  { title: 'Sweet Dreams (Are Made of This)', artist: 'Eurythmics', year: 1983, previewUrl: '' },
  { title: 'Total Eclipse of the Heart', artist: 'Bonnie Tyler', year: 1983, previewUrl: '' },
  { title: 'Flashdance... What a Feeling', artist: 'Irene Cara', year: 1983, previewUrl: '' },
  { title: 'True', artist: 'Spandau Ballet', year: 1983, previewUrl: '' },
  { title: 'Blue Monday', artist: 'New Order', year: 1983, previewUrl: '' },
  { title: 'Purple Rain', artist: 'Prince', year: 1984, previewUrl: '' },
  { title: 'When Doves Cry', artist: 'Prince', year: 1984, previewUrl: '' },
  { title: 'Like a Virgin', artist: 'Madonna', year: 1984, previewUrl: '' },
  { title: 'Borderline', artist: 'Madonna', year: 1984, previewUrl: '' },
  { title: 'Wake Me Up Before You Go-Go', artist: 'Wham!', year: 1984, previewUrl: '' },
  { title: 'Jump', artist: 'Van Halen', year: 1984, previewUrl: '' },
  { title: 'Careless Whisper', artist: 'George Michael', year: 1984, previewUrl: '' },
  { title: 'What\'s Love Got to Do with It', artist: 'Tina Turner', year: 1984, previewUrl: '' },
  { title: 'Time After Time', artist: 'Cyndi Lauper', year: 1984, previewUrl: '' },
  { title: 'Footloose', artist: 'Kenny Loggins', year: 1984, previewUrl: '' },
  { title: 'Do They Know It\'s Christmas?', artist: 'Band Aid', year: 1984, previewUrl: '' },
  { title: 'Take On Me', artist: 'a-ha', year: 1985, previewUrl: '' },
  { title: 'Walking on Sunshine', artist: 'Katrina and the Waves', year: 1985, previewUrl: '' },
  { title: 'Don\'t You (Forget About Me)', artist: 'Simple Minds', year: 1985, previewUrl: '' },
  { title: 'Money for Nothing', artist: 'Dire Straits', year: 1985, previewUrl: '' },
  { title: 'We Are the World', artist: 'USA for Africa', year: 1985, previewUrl: '' },
  { title: 'I Want to Know What Love Is', artist: 'Foreigner', year: 1984, previewUrl: '' },
  { title: 'Power of Love', artist: 'Huey Lewis and the News', year: 1985, previewUrl: '' },
  { title: 'West End Girls', artist: 'Pet Shop Boys', year: 1985, previewUrl: '' },
  { title: 'Livin\' on a Prayer', artist: 'Bon Jovi', year: 1986, previewUrl: '' },
  { title: 'Papa Don\'t Preach', artist: 'Madonna', year: 1986, previewUrl: '' },
  { title: 'Sledgehammer', artist: 'Peter Gabriel', year: 1986, previewUrl: '' },
  { title: 'Walk Like an Egyptian', artist: 'The Bangles', year: 1986, previewUrl: '' },
  { title: 'Addicted to Love', artist: 'Robert Palmer', year: 1985, previewUrl: '' },
  { title: 'Take My Breath Away', artist: 'Berlin', year: 1986, previewUrl: '' },
  { title: 'Sweet Child O\' Mine', artist: 'Guns N\' Roses', year: 1987, previewUrl: '' },
  { title: 'With or Without You', artist: 'U2', year: 1987, previewUrl: '' },
  { title: 'I Still Haven\'t Found What I\'m Looking For', artist: 'U2', year: 1987, previewUrl: '' },
  { title: 'Never Gonna Give You Up', artist: 'Rick Astley', year: 1987, previewUrl: '' },
  { title: 'Need You Tonight', artist: 'INXS', year: 1987, previewUrl: '' },
  { title: 'Faith', artist: 'George Michael', year: 1987, previewUrl: '' },
  { title: 'Bad', artist: 'Michael Jackson', year: 1987, previewUrl: '' },
  { title: 'The Way You Make Me Feel', artist: 'Michael Jackson', year: 1987, previewUrl: '' },
  { title: 'Push It', artist: 'Salt-N-Pepa', year: 1987, previewUrl: '' },
  { title: 'Never Tear Us Apart', artist: 'INXS', year: 1988, previewUrl: '' },
  { title: 'Sweet Dreams', artist: 'Eurythmics', year: 1983, previewUrl: '' },
  { title: 'Fast Car', artist: 'Tracy Chapman', year: 1988, previewUrl: '' },
  { title: 'Don\'t Worry, Be Happy', artist: 'Bobby McFerrin', year: 1988, previewUrl: '' },
  { title: 'Straight Outta Compton', artist: 'N.W.A.', year: 1988, previewUrl: '' },
  { title: 'Like a Prayer', artist: 'Madonna', year: 1989, previewUrl: '' },
  { title: 'Eternal Flame', artist: 'The Bangles', year: 1989, previewUrl: '' },
  { title: 'Every Rose Has Its Thorn', artist: 'Poison', year: 1988, previewUrl: '' },
  { title: 'Fight the Power', artist: 'Public Enemy', year: 1989, previewUrl: '' },
  { title: 'Love Shack', artist: 'The B-52\'s', year: 1989, previewUrl: '' },
  { title: 'Ride on Time', artist: 'Black Box', year: 1989, previewUrl: '' },
  { title: 'Back to Life', artist: 'Soul II Soul', year: 1989, previewUrl: '' },

  // 1990s
  { title: 'Nothing Compares 2 U', artist: 'Sinéad O\'Connor', year: 1990, previewUrl: '' },
  { title: 'Vogue', artist: 'Madonna', year: 1990, previewUrl: '' },
  { title: 'Ice Ice Baby', artist: 'Vanilla Ice', year: 1990, previewUrl: '' },
  { title: 'U Can\'t Touch This', artist: 'MC Hammer', year: 1990, previewUrl: '' },
  { title: 'Unbelievable', artist: 'EMF', year: 1990, previewUrl: '' },
  { title: 'Groove Is in the Heart', artist: 'Deee-Lite', year: 1990, previewUrl: '' },
  { title: 'Smells Like Teen Spirit', artist: 'Nirvana', year: 1991, previewUrl: '' },
  { title: 'Losing My Religion', artist: 'R.E.M.', year: 1991, previewUrl: '' },
  { title: 'Under the Bridge', artist: 'Red Hot Chili Peppers', year: 1991, previewUrl: '' },
  { title: '(Everything I Do) I Do It for You', artist: 'Bryan Adams', year: 1991, previewUrl: '' },
  { title: 'Enter Sandman', artist: 'Metallica', year: 1991, previewUrl: '' },
  { title: 'November Rain', artist: 'Guns N\' Roses', year: 1991, previewUrl: '' },
  { title: 'Baby Got Back', artist: 'Sir Mix-a-Lot', year: 1992, previewUrl: '' },
  { title: 'End of the Road', artist: 'Boyz II Men', year: 1992, previewUrl: '' },
  { title: 'I Will Always Love You', artist: 'Whitney Houston', year: 1992, previewUrl: '' },
  { title: 'Jump', artist: 'Kris Kross', year: 1992, previewUrl: '' },
  { title: 'Creep', artist: 'Radiohead', year: 1992, previewUrl: '' },
  { title: 'Informer', artist: 'Snow', year: 1992, previewUrl: '' },
  { title: 'Tears in Heaven', artist: 'Eric Clapton', year: 1992, previewUrl: '' },
  { title: 'Black or White', artist: 'Michael Jackson', year: 1991, previewUrl: '' },
  { title: 'Whoomp! (There It Is)', artist: 'Tag Team', year: 1993, previewUrl: '' },
  { title: 'Dreamlover', artist: 'Mariah Carey', year: 1993, previewUrl: '' },
  { title: 'No Rain', artist: 'Blind Melon', year: 1993, previewUrl: '' },
  { title: 'What\'s Up?', artist: '4 Non Blondes', year: 1993, previewUrl: '' },
  { title: 'All That She Wants', artist: 'Ace of Base', year: 1992, previewUrl: '' },
  { title: 'The Sign', artist: 'Ace of Base', year: 1993, previewUrl: '' },
  { title: 'I Will Always Love You', artist: 'Whitney Houston', year: 1992, previewUrl: '' },
  { title: 'Zombie', artist: 'The Cranberries', year: 1994, previewUrl: '' },
  { title: 'Wonderwall', artist: 'Oasis', year: 1995, previewUrl: '' },
  { title: 'Don\'t Look Back in Anger', artist: 'Oasis', year: 1996, previewUrl: '' },
  { title: 'Common People', artist: 'Pulp', year: 1995, previewUrl: '' },
  { title: 'Waterfalls', artist: 'TLC', year: 1994, previewUrl: '' },
  { title: 'Loser', artist: 'Beck', year: 1993, previewUrl: '' },
  { title: 'Gangsta\'s Paradise', artist: 'Coolio', year: 1995, previewUrl: '' },
  { title: 'Kiss from a Rose', artist: 'Seal', year: 1994, previewUrl: '' },
  { title: 'I\'ll Be There for You', artist: 'The Rembrandts', year: 1995, previewUrl: '' },
  { title: 'Fantasy', artist: 'Mariah Carey', year: 1995, previewUrl: '' },
  { title: 'Macarena', artist: 'Los del Río', year: 1995, previewUrl: '' },
  { title: 'Killing Me Softly', artist: 'Fugees', year: 1996, previewUrl: '' },
  { title: 'California Love', artist: '2Pac ft. Dr. Dre', year: 1995, previewUrl: '' },
  { title: 'No Diggity', artist: 'Blackstreet', year: 1996, previewUrl: '' },
  { title: 'Firestarter', artist: 'The Prodigy', year: 1996, previewUrl: '' },
  { title: 'Wannabe', artist: 'Spice Girls', year: 1996, previewUrl: '' },
  { title: 'Say You\'ll Be There', artist: 'Spice Girls', year: 1996, previewUrl: '' },
  { title: 'Bitter Sweet Symphony', artist: 'The Verve', year: 1997, previewUrl: '' },
  { title: 'Tubthumping', artist: 'Chumbawamba', year: 1997, previewUrl: '' },
  { title: 'Candle in the Wind 1997', artist: 'Elton John', year: 1997, previewUrl: '' },
  { title: 'MMMBop', artist: 'Hanson', year: 1997, previewUrl: '' },
  { title: 'Barbie Girl', artist: 'Aqua', year: 1997, previewUrl: '' },
  { title: 'Men in Black', artist: 'Will Smith', year: 1997, previewUrl: '' },
  { title: 'I\'ll Be Missing You', artist: 'Puff Daddy ft. Faith Evans', year: 1997, previewUrl: '' },
  { title: 'Mo Money Mo Problems', artist: 'The Notorious B.I.G.', year: 1997, previewUrl: '' },
  { title: 'Torn', artist: 'Natalie Imbruglia', year: 1997, previewUrl: '' },
  { title: 'My Heart Will Go On', artist: 'Celine Dion', year: 1997, previewUrl: '' },
  { title: '...Baby One More Time', artist: 'Britney Spears', year: 1998, previewUrl: '' },
  { title: 'Believe', artist: 'Cher', year: 1998, previewUrl: '' },
  { title: 'Ray of Light', artist: 'Madonna', year: 1998, previewUrl: '' },
  { title: 'Brimful of Asha', artist: 'Cornershop', year: 1997, previewUrl: '' },
  { title: 'Gettin\' Jiggy wit It', artist: 'Will Smith', year: 1997, previewUrl: '' },
  { title: 'Praise You', artist: 'Fatboy Slim', year: 1998, previewUrl: '' },
  { title: 'Livin\' la Vida Loca', artist: 'Ricky Martin', year: 1999, previewUrl: '' },
  { title: 'No Scrubs', artist: 'TLC', year: 1999, previewUrl: '' },
  { title: 'Say My Name', artist: 'Destiny\'s Child', year: 1999, previewUrl: '' },
  { title: 'Genie in a Bottle', artist: 'Christina Aguilera', year: 1999, previewUrl: '' },
  { title: '...Baby One More Time', artist: 'Britney Spears', year: 1998, previewUrl: '' },
  { title: 'Smooth', artist: 'Santana ft. Rob Thomas', year: 1999, previewUrl: '' },
  { title: 'Bills, Bills, Bills', artist: 'Destiny\'s Child', year: 1999, previewUrl: '' },
  { title: 'Steal My Sunshine', artist: 'Len', year: 1999, previewUrl: '' },
  { title: 'Scar Tissue', artist: 'Red Hot Chili Peppers', year: 1999, previewUrl: '' },

  // 2000s
  { title: 'Oops!... I Did It Again', artist: 'Britney Spears', year: 2000, previewUrl: '' },
  { title: 'Bye Bye Bye', artist: '*NSYNC', year: 2000, previewUrl: '' },
  { title: 'Teenage Dirtbag', artist: 'Wheatus', year: 2000, previewUrl: '' },
  { title: 'It Wasn\'t Me', artist: 'Shaggy ft. RikRok', year: 2000, previewUrl: '' },
  { title: 'Yellow', artist: 'Coldplay', year: 2000, previewUrl: '' },
  { title: 'Beautiful Day', artist: 'U2', year: 2000, previewUrl: '' },
  { title: 'Independent Women', artist: 'Destiny\'s Child', year: 2000, previewUrl: '' },
  { title: 'Ms. Jackson', artist: 'OutKast', year: 2000, previewUrl: '' },
  { title: 'Who Let the Dogs Out', artist: 'Baha Men', year: 2000, previewUrl: '' },
  { title: 'Hanging by a Moment', artist: 'Lifehouse', year: 2000, previewUrl: '' },
  { title: 'Fallin\'', artist: 'Alicia Keys', year: 2001, previewUrl: '' },
  { title: 'Drops of Jupiter', artist: 'Train', year: 2001, previewUrl: '' },
  { title: 'Lady Marmalade', artist: 'Christina Aguilera, Lil\' Kim, Mya & Pink', year: 2001, previewUrl: '' },
  { title: 'Hey Ya!', artist: 'OutKast', year: 2003, previewUrl: '' },
  { title: 'Clocks', artist: 'Coldplay', year: 2002, previewUrl: '' },
  { title: 'Bring Me to Life', artist: 'Evanescence', year: 2003, previewUrl: '' },
  { title: 'In Da Club', artist: '50 Cent', year: 2003, previewUrl: '' },
  { title: 'Crazy in Love', artist: 'Beyoncé ft. Jay-Z', year: 2003, previewUrl: '' },
  { title: 'Seven Nation Army', artist: 'The White Stripes', year: 2003, previewUrl: '' },
  { title: 'Mr. Brightside', artist: 'The Killers', year: 2003, previewUrl: '' },
  { title: 'Toxic', artist: 'Britney Spears', year: 2003, previewUrl: '' },
  { title: 'Yeah!', artist: 'Usher ft. Lil Jon & Ludacris', year: 2004, previewUrl: '' },
  { title: 'Burn', artist: 'Usher', year: 2004, previewUrl: '' },
  { title: 'Since U Been Gone', artist: 'Kelly Clarkson', year: 2004, previewUrl: '' },
  { title: 'Mr. Brightside', artist: 'The Killers', year: 2004, previewUrl: '' },
  { title: 'Hey Ya!', artist: 'OutKast', year: 2003, previewUrl: '' },
  { title: 'American Idiot', artist: 'Green Day', year: 2004, previewUrl: '' },
  { title: 'Feel Good Inc.', artist: 'Gorillaz', year: 2005, previewUrl: '' },
  { title: 'Gold Digger', artist: 'Kanye West ft. Jamie Foxx', year: 2005, previewUrl: '' },
  { title: 'Hollaback Girl', artist: 'Gwen Stefani', year: 2005, previewUrl: '' },
  { title: 'Don\'t Cha', artist: 'The Pussycat Dolls', year: 2005, previewUrl: '' },
  { title: 'My Humps', artist: 'The Black Eyed Peas', year: 2005, previewUrl: '' },
  { title: 'I\'m a Believer', artist: 'Smash Mouth', year: 2001, previewUrl: '' },
  { title: 'Crazy', artist: 'Gnarls Barkley', year: 2006, previewUrl: '' },
  { title: 'Bad Day', artist: 'Daniel Powter', year: 2005, previewUrl: '' },
  { title: 'Sexyback', artist: 'Justin Timberlake', year: 2006, previewUrl: '' },
  { title: 'Irreplaceable', artist: 'Beyoncé', year: 2006, previewUrl: '' },
  { title: 'Chasing Cars', artist: 'Snow Patrol', year: 2006, previewUrl: '' },
  { title: 'Hips Don\'t Lie', artist: 'Shakira ft. Wyclef Jean', year: 2006, previewUrl: '' },
  { title: 'Umbrella', artist: 'Rihanna ft. Jay-Z', year: 2007, previewUrl: '' },
  { title: 'Apologize', artist: 'Timbaland ft. OneRepublic', year: 2007, previewUrl: '' },
  { title: 'Low', artist: 'Flo Rida ft. T-Pain', year: 2007, previewUrl: '' },
  { title: 'Big Girls Don\'t Cry', artist: 'Fergie', year: 2007, previewUrl: '' },
  { title: 'Stronger', artist: 'Kanye West', year: 2007, previewUrl: '' },
  { title: 'Bleeding Love', artist: 'Leona Lewis', year: 2007, previewUrl: '' },
  { title: 'Rehab', artist: 'Amy Winehouse', year: 2006, previewUrl: '' },
  { title: 'Valerie', artist: 'Mark Ronson ft. Amy Winehouse', year: 2007, previewUrl: '' },
  { title: 'Love in This Club', artist: 'Usher ft. Young Jeezy', year: 2008, previewUrl: '' },
  { title: 'I Kissed a Girl', artist: 'Katy Perry', year: 2008, previewUrl: '' },
  { title: 'Viva La Vida', artist: 'Coldplay', year: 2008, previewUrl: '' },
  { title: 'Poker Face', artist: 'Lady Gaga', year: 2008, previewUrl: '' },
  { title: 'Just Dance', artist: 'Lady Gaga ft. Colby O\'Donis', year: 2008, previewUrl: '' },
  { title: 'Single Ladies (Put a Ring on It)', artist: 'Beyoncé', year: 2008, previewUrl: '' },
  { title: 'Halo', artist: 'Beyoncé', year: 2008, previewUrl: '' },
  { title: 'Whatcha Say', artist: 'Jason Derulo', year: 2009, previewUrl: '' },
  { title: 'Empire State of Mind', artist: 'Jay-Z ft. Alicia Keys', year: 2009, previewUrl: '' },
  { title: 'I Gotta Feeling', artist: 'The Black Eyed Peas', year: 2009, previewUrl: '' },
  { title: 'Boom Boom Pow', artist: 'The Black Eyed Peas', year: 2009, previewUrl: '' },
  { title: 'Use Somebody', artist: 'Kings of Leon', year: 2008, previewUrl: '' },
  { title: 'Sex on Fire', artist: 'Kings of Leon', year: 2008, previewUrl: '' },
  { title: 'Fireflies', artist: 'Owl City', year: 2009, previewUrl: '' },
  { title: 'TiK ToK', artist: 'Kesha', year: 2009, previewUrl: '' },
  { title: 'Love Story', artist: 'Taylor Swift', year: 2008, previewUrl: '' },
  { title: 'Bad Romance', artist: 'Lady Gaga', year: 2009, previewUrl: '' },

  // 2010s
  { title: 'California Gurls', artist: 'Katy Perry ft. Snoop Dogg', year: 2010, previewUrl: '' },
  { title: 'Teenage Dream', artist: 'Katy Perry', year: 2010, previewUrl: '' },
  { title: 'Firework', artist: 'Katy Perry', year: 2010, previewUrl: '' },
  { title: 'Dynamite', artist: 'Taio Cruz', year: 2010, previewUrl: '' },
  { title: 'Love the Way You Lie', artist: 'Eminem ft. Rihanna', year: 2010, previewUrl: '' },
  { title: 'Not Afraid', artist: 'Eminem', year: 2010, previewUrl: '' },
  { title: 'Rolling in the Deep', artist: 'Adele', year: 2010, previewUrl: '' },
  { title: 'Someone Like You', artist: 'Adele', year: 2011, previewUrl: '' },
  { title: 'Set Fire to the Rain', artist: 'Adele', year: 2011, previewUrl: '' },
  { title: 'Party Rock Anthem', artist: 'LMFAO', year: 2011, previewUrl: '' },
  { title: 'Moves Like Jagger', artist: 'Maroon 5 ft. Christina Aguilera', year: 2011, previewUrl: '' },
  { title: 'Call Me Maybe', artist: 'Carly Rae Jepsen', year: 2011, previewUrl: '' },
  { title: 'Somebody That I Used to Know', artist: 'Gotye ft. Kimbra', year: 2011, previewUrl: '' },
  { title: 'We Found Love', artist: 'Rihanna ft. Calvin Harris', year: 2011, previewUrl: '' },
  { title: 'Super Bass', artist: 'Nicki Minaj', year: 2011, previewUrl: '' },
  { title: 'Pumped Up Kicks', artist: 'Foster the People', year: 2010, previewUrl: '' },
  { title: 'Price Tag', artist: 'Jessie J ft. B.o.B', year: 2011, previewUrl: '' },
  { title: 'Payphone', artist: 'Maroon 5 ft. Wiz Khalifa', year: 2012, previewUrl: '' },
  { title: 'We Are Young', artist: 'fun. ft. Janelle Monáe', year: 2011, previewUrl: '' },
  { title: 'Gangnam Style', artist: 'Psy', year: 2012, previewUrl: '' },
  { title: 'Some Nights', artist: 'fun.', year: 2012, previewUrl: '' },
  { title: 'Thrift Shop', artist: 'Macklemore & Ryan Lewis ft. Wanz', year: 2012, previewUrl: '' },
  { title: 'Ho Hey', artist: 'The Lumineers', year: 2012, previewUrl: '' },
  { title: 'Get Lucky', artist: 'Daft Punk ft. Pharrell Williams', year: 2013, previewUrl: '' },
  { title: 'Happy', artist: 'Pharrell Williams', year: 2013, previewUrl: '' },
  { title: 'Blurred Lines', artist: 'Robin Thicke ft. T.I. & Pharrell', year: 2013, previewUrl: '' },
  { title: 'Royals', artist: 'Lorde', year: 2013, previewUrl: '' },
  { title: 'Wrecking Ball', artist: 'Miley Cyrus', year: 2013, previewUrl: '' },
  { title: 'Roar', artist: 'Katy Perry', year: 2013, previewUrl: '' },
  { title: 'Dark Horse', artist: 'Katy Perry ft. Juicy J', year: 2013, previewUrl: '' },
  { title: 'Radioactive', artist: 'Imagine Dragons', year: 2012, previewUrl: '' },
  { title: 'Let Her Go', artist: 'Passenger', year: 2012, previewUrl: '' },
  { title: 'Counting Stars', artist: 'OneRepublic', year: 2013, previewUrl: '' },
  { title: 'Wake Me Up', artist: 'Avicii', year: 2013, previewUrl: '' },
  { title: 'Hey Brother', artist: 'Avicii', year: 2013, previewUrl: '' },
  { title: 'Let It Go', artist: 'Idina Menzel', year: 2013, previewUrl: '' },
  { title: 'Stay with Me', artist: 'Sam Smith', year: 2014, previewUrl: '' },
  { title: 'Uptown Funk', artist: 'Mark Ronson ft. Bruno Mars', year: 2014, previewUrl: '' },
  { title: 'Shake It Off', artist: 'Taylor Swift', year: 2014, previewUrl: '' },
  { title: 'Blank Space', artist: 'Taylor Swift', year: 2014, previewUrl: '' },
  { title: 'Bad Blood', artist: 'Taylor Swift', year: 2014, previewUrl: '' },
  { title: 'All About That Bass', artist: 'Meghan Trainor', year: 2014, previewUrl: '' },
  { title: 'Thinking Out Loud', artist: 'Ed Sheeran', year: 2014, previewUrl: '' },
  { title: 'Photograph', artist: 'Ed Sheeran', year: 2014, previewUrl: '' },
  { title: 'Chandelier', artist: 'Sia', year: 2014, previewUrl: '' },
  { title: 'Fancy', artist: 'Iggy Azalea ft. Charli XCX', year: 2014, previewUrl: '' },
  { title: 'Problem', artist: 'Ariana Grande ft. Iggy Azalea', year: 2014, previewUrl: '' },
  { title: 'Sugar', artist: 'Maroon 5', year: 2014, previewUrl: '' },
  { title: 'Hello', artist: 'Adele', year: 2015, previewUrl: '' },
  { title: 'Can\'t Feel My Face', artist: 'The Weeknd', year: 2015, previewUrl: '' },
  { title: 'The Hills', artist: 'The Weeknd', year: 2015, previewUrl: '' },
  { title: 'Sorry', artist: 'Justin Bieber', year: 2015, previewUrl: '' },
  { title: 'What Do You Mean?', artist: 'Justin Bieber', year: 2015, previewUrl: '' },
  { title: 'Love Yourself', artist: 'Justin Bieber', year: 2015, previewUrl: '' },
  { title: 'Hotline Bling', artist: 'Drake', year: 2015, previewUrl: '' },
  { title: 'Stressed Out', artist: 'Twenty One Pilots', year: 2015, previewUrl: '' },
  { title: 'See You Again', artist: 'Wiz Khalifa ft. Charlie Puth', year: 2015, previewUrl: '' },
  { title: 'Lean On', artist: 'Major Lazer & DJ Snake ft. MØ', year: 2015, previewUrl: '' },
  { title: 'Bad Blood', artist: 'Taylor Swift ft. Kendrick Lamar', year: 2015, previewUrl: '' },
  { title: 'Cheerleader', artist: 'OMI', year: 2014, previewUrl: '' },
  { title: 'Work', artist: 'Rihanna ft. Drake', year: 2016, previewUrl: '' },
  { title: 'Closer', artist: 'The Chainsmokers ft. Halsey', year: 2016, previewUrl: '' },
  { title: 'Don\'t Let Me Down', artist: 'The Chainsmokers ft. Daya', year: 2016, previewUrl: '' },
  { title: 'One Dance', artist: 'Drake ft. WizKid & Kyla', year: 2016, previewUrl: '' },
  { title: 'Cheap Thrills', artist: 'Sia ft. Sean Paul', year: 2016, previewUrl: '' },
  { title: 'Can\'t Stop the Feeling!', artist: 'Justin Timberlake', year: 2016, previewUrl: '' },
  { title: 'Heathens', artist: 'Twenty One Pilots', year: 2016, previewUrl: '' },
  { title: 'Side to Side', artist: 'Ariana Grande ft. Nicki Minaj', year: 2016, previewUrl: '' },
  { title: 'Formation', artist: 'Beyoncé', year: 2016, previewUrl: '' },
  { title: 'Starboy', artist: 'The Weeknd ft. Daft Punk', year: 2016, previewUrl: '' },
  { title: '7 Years', artist: 'Lukas Graham', year: 2015, previewUrl: '' },
  { title: 'Despacito', artist: 'Luis Fonsi & Daddy Yankee', year: 2017, previewUrl: '' },
  { title: 'Shape of You', artist: 'Ed Sheeran', year: 2017, previewUrl: '' },
  { title: 'Perfect', artist: 'Ed Sheeran', year: 2017, previewUrl: '' },
  { title: 'Humble', artist: 'Kendrick Lamar', year: 2017, previewUrl: '' },
  { title: 'Bad and Boujee', artist: 'Migos ft. Lil Uzi Vert', year: 2016, previewUrl: '' },
  { title: 'That\'s What I Like', artist: 'Bruno Mars', year: 2016, previewUrl: '' },
  { title: '24K Magic', artist: 'Bruno Mars', year: 2016, previewUrl: '' },
  { title: 'Believer', artist: 'Imagine Dragons', year: 2017, previewUrl: '' },
  { title: 'Thunder', artist: 'Imagine Dragons', year: 2017, previewUrl: '' },
  { title: 'Attention', artist: 'Charlie Puth', year: 2017, previewUrl: '' },
  { title: 'Rockstar', artist: 'Post Malone ft. 21 Savage', year: 2017, previewUrl: '' },
  { title: 'Congratulations', artist: 'Post Malone ft. Quavo', year: 2016, previewUrl: '' },
  { title: 'Havana', artist: 'Camila Cabello ft. Young Thug', year: 2017, previewUrl: '' },
  { title: 'New Rules', artist: 'Dua Lipa', year: 2017, previewUrl: '' },
  { title: 'God\'s Plan', artist: 'Drake', year: 2018, previewUrl: '' },
  { title: 'In My Feelings', artist: 'Drake', year: 2018, previewUrl: '' },
  { title: 'Nice for What', artist: 'Drake', year: 2018, previewUrl: '' },
  { title: 'Perfect', artist: 'Ed Sheeran', year: 2017, previewUrl: '' },
  { title: 'Shallow', artist: 'Lady Gaga & Bradley Cooper', year: 2018, previewUrl: '' },
  { title: 'Thank U, Next', artist: 'Ariana Grande', year: 2018, previewUrl: '' },
  { title: '7 Rings', artist: 'Ariana Grande', year: 2019, previewUrl: '' },
  { title: 'Old Town Road', artist: 'Lil Nas X ft. Billy Ray Cyrus', year: 2019, previewUrl: '' },
  { title: 'Bad Guy', artist: 'Billie Eilish', year: 2019, previewUrl: '' },
  { title: 'Senorita', artist: 'Shawn Mendes & Camila Cabello', year: 2019, previewUrl: '' },
  { title: 'Someone You Loved', artist: 'Lewis Capaldi', year: 2018, previewUrl: '' },
  { title: 'Sunflower', artist: 'Post Malone & Swae Lee', year: 2018, previewUrl: '' },
  { title: 'Truth Hurts', artist: 'Lizzo', year: 2017, previewUrl: '' },
  { title: 'Good as Hell', artist: 'Lizzo', year: 2016, previewUrl: '' },
  { title: 'Watermelon Sugar', artist: 'Harry Styles', year: 2019, previewUrl: '' },
  { title: 'Adore You', artist: 'Harry Styles', year: 2019, previewUrl: '' },
  { title: 'Memories', artist: 'Maroon 5', year: 2019, previewUrl: '' },
  { title: 'Circles', artist: 'Post Malone', year: 2019, previewUrl: '' },
  { title: 'Dance Monkey', artist: 'Tones and I', year: 2019, previewUrl: '' },

  // 2020s
  { title: 'Blinding Lights', artist: 'The Weeknd', year: 2019, previewUrl: '' },
  { title: 'Save Your Tears', artist: 'The Weeknd', year: 2020, previewUrl: '' },
  { title: 'Heartless', artist: 'The Weeknd', year: 2019, previewUrl: '' },
  { title: 'Don\'t Start Now', artist: 'Dua Lipa', year: 2019, previewUrl: '' },
  { title: 'Physical', artist: 'Dua Lipa', year: 2020, previewUrl: '' },
  { title: 'Levitating', artist: 'Dua Lipa', year: 2020, previewUrl: '' },
  { title: 'Break My Heart', artist: 'Dua Lipa', year: 2020, previewUrl: '' },
  { title: 'Watermelon Sugar', artist: 'Harry Styles', year: 2019, previewUrl: '' },
  { title: 'The Box', artist: 'Roddy Ricch', year: 2019, previewUrl: '' },
  { title: 'Savage', artist: 'Megan Thee Stallion', year: 2020, previewUrl: '' },
  { title: 'WAP', artist: 'Cardi B ft. Megan Thee Stallion', year: 2020, previewUrl: '' },
  { title: 'Rockstar', artist: 'DaBaby ft. Roddy Ricch', year: 2020, previewUrl: '' },
  { title: 'Say So', artist: 'Doja Cat', year: 2019, previewUrl: '' },
  { title: 'Dynamite', artist: 'BTS', year: 2020, previewUrl: '' },
  { title: 'Butter', artist: 'BTS', year: 2021, previewUrl: '' },
  { title: 'Mood', artist: '24kGoldn ft. iann dior', year: 2020, previewUrl: '' },
  { title: 'Watermelon Sugar', artist: 'Harry Styles', year: 2019, previewUrl: '' },
  { title: 'Good 4 U', artist: 'Olivia Rodrigo', year: 2021, previewUrl: '' },
  { title: 'drivers license', artist: 'Olivia Rodrigo', year: 2021, previewUrl: '' },
  { title: 'deja vu', artist: 'Olivia Rodrigo', year: 2021, previewUrl: '' },
  { title: 'Stay', artist: 'The Kid LAROI & Justin Bieber', year: 2021, previewUrl: '' },
  { title: 'Peaches', artist: 'Justin Bieber ft. Daniel Caesar & Giveon', year: 2021, previewUrl: '' },
  { title: 'Kiss Me More', artist: 'Doja Cat ft. SZA', year: 2021, previewUrl: '' },
  { title: 'Heat Waves', artist: 'Glass Animals', year: 2020, previewUrl: '' },
  { title: 'Montero (Call Me By Your Name)', artist: 'Lil Nas X', year: 2021, previewUrl: '' },
  { title: 'Industry Baby', artist: 'Lil Nas X ft. Jack Harlow', year: 2021, previewUrl: '' },
  { title: 'Bad Habits', artist: 'Ed Sheeran', year: 2021, previewUrl: '' },
  { title: 'Shivers', artist: 'Ed Sheeran', year: 2021, previewUrl: '' },
  { title: 'Cruel Summer', artist: 'Taylor Swift', year: 2019, previewUrl: '' },
  { title: 'Anti-Hero', artist: 'Taylor Swift', year: 2022, previewUrl: '' },
  { title: 'As It Was', artist: 'Harry Styles', year: 2022, previewUrl: '' },
  { title: 'About Damn Time', artist: 'Lizzo', year: 2022, previewUrl: '' },
  { title: 'Running Up That Hill', artist: 'Kate Bush', year: 1985, previewUrl: '' },
  { title: 'First Class', artist: 'Jack Harlow', year: 2022, previewUrl: '' },
  { title: 'Unholy', artist: 'Sam Smith & Kim Petras', year: 2022, previewUrl: '' },
  { title: 'Kill Bill', artist: 'SZA', year: 2022, previewUrl: '' },
  { title: 'Flowers', artist: 'Miley Cyrus', year: 2023, previewUrl: '' },
  { title: 'Vampire', artist: 'Olivia Rodrigo', year: 2023, previewUrl: '' },
  { title: 'Last Night', artist: 'Morgan Wallen', year: 2023, previewUrl: '' },
  { title: 'Calm Down', artist: 'Rema & Selena Gomez', year: 2022, previewUrl: '' },
  { title: 'Cupid', artist: 'FIFTY FIFTY', year: 2023, previewUrl: '' },
  { title: 'Paint the Town Red', artist: 'Doja Cat', year: 2023, previewUrl: '' },
  { title: 'Greedy', artist: 'Tate McRae', year: 2023, previewUrl: '' },
  { title: 'Cruel Summer', artist: 'Taylor Swift', year: 2019, previewUrl: '' },
  { title: 'Espresso', artist: 'Sabrina Carpenter', year: 2024, previewUrl: '' },
  { title: 'Please Please Please', artist: 'Sabrina Carpenter', year: 2024, previewUrl: '' },
  { title: 'Texas Hold \'Em', artist: 'Beyoncé', year: 2024, previewUrl: '' },
  { title: 'Lose Control', artist: 'Teddy Swims', year: 2023, previewUrl: '' },
  { title: 'I Remember Everything', artist: 'Zach Bryan ft. Kacey Musgraves', year: 2023, previewUrl: '' },

  // Classic rock / indie / miscellaneous gems (spread across decades for variety)
  { title: 'Riders on the Storm', artist: 'The Doors', year: 1971, previewUrl: '' },
  { title: 'Brown Sugar', artist: 'The Rolling Stones', year: 1971, previewUrl: '' },
  { title: 'Layla', artist: 'Derek and the Dominos', year: 1970, previewUrl: '' },
  { title: 'Piano Man', artist: 'Billy Joel', year: 1973, previewUrl: '' },
  { title: 'We Will Rock You', artist: 'Queen', year: 1977, previewUrl: '' },
  { title: 'We Are the Champions', artist: 'Queen', year: 1977, previewUrl: '' },
  { title: 'Don\'t Stop Me Now', artist: 'Queen', year: 1978, previewUrl: '' },
  { title: 'Under Pressure', artist: 'Queen & David Bowie', year: 1981, previewUrl: '' },
  { title: 'Space Oddity', artist: 'David Bowie', year: 1969, previewUrl: '' },
  { title: 'Life on Mars?', artist: 'David Bowie', year: 1971, previewUrl: '' },
  { title: 'Let\'s Dance', artist: 'David Bowie', year: 1983, previewUrl: '' },
  { title: 'Life in the Fast Lane', artist: 'Eagles', year: 1976, previewUrl: '' },
  { title: 'Take It Easy', artist: 'Eagles', year: 1972, previewUrl: '' },
  { title: 'New York, New York', artist: 'Frank Sinatra', year: 1977, previewUrl: '' },
  { title: 'My Way', artist: 'Frank Sinatra', year: 1969, previewUrl: '' },
  { title: 'Fly Me to the Moon', artist: 'Frank Sinatra', year: 1964, previewUrl: '' },
  { title: 'I Got You (I Feel Good)', artist: 'James Brown', year: 1965, previewUrl: '' },
  { title: 'Papa\'s Got a Brand New Bag', artist: 'James Brown', year: 1965, previewUrl: '' },
  { title: 'Superstar', artist: 'The Carpenters', year: 1971, previewUrl: '' },
  { title: 'Whole Lotta Love', artist: 'Led Zeppelin', year: 1969, previewUrl: '' },
  { title: 'Kashmir', artist: 'Led Zeppelin', year: 1975, previewUrl: '' },
  { title: 'Black Dog', artist: 'Led Zeppelin', year: 1971, previewUrl: '' },
  { title: 'Money', artist: 'Pink Floyd', year: 1973, previewUrl: '' },
  { title: 'Comfortably Numb', artist: 'Pink Floyd', year: 1979, previewUrl: '' },
  { title: 'Wish You Were Here', artist: 'Pink Floyd', year: 1975, previewUrl: '' },
  { title: 'Paranoid', artist: 'Black Sabbath', year: 1970, previewUrl: '' },
  { title: 'Iron Man', artist: 'Black Sabbath', year: 1970, previewUrl: '' },
  { title: 'Crazy Train', artist: 'Ozzy Osbourne', year: 1980, previewUrl: '' },
  { title: 'Rebel Rebel', artist: 'David Bowie', year: 1974, previewUrl: '' },
  { title: 'Walk This Way', artist: 'Aerosmith', year: 1975, previewUrl: '' },
  { title: 'Sultans of Swing', artist: 'Dire Straits', year: 1978, previewUrl: '' },
  { title: 'More Than a Feeling', artist: 'Boston', year: 1976, previewUrl: '' },
  { title: 'Carry On Wayward Son', artist: 'Kansas', year: 1976, previewUrl: '' },
  { title: 'Don\'t Fear the Reaper', artist: 'Blue Öyster Cult', year: 1976, previewUrl: '' },
  { title: 'Barracuda', artist: 'Heart', year: 1977, previewUrl: '' },
  { title: 'I Want You Back', artist: 'The Jackson 5', year: 1969, previewUrl: '' },
  { title: 'ABC', artist: 'The Jackson 5', year: 1970, previewUrl: '' },
  { title: 'I\'ll Be There', artist: 'The Jackson 5', year: 1970, previewUrl: '' },
  { title: 'Ain\'t No Mountain High Enough', artist: 'Marvin Gaye & Tammi Terrell', year: 1967, previewUrl: '' },
  { title: 'I Heard It Through the Grapevine', artist: 'Marvin Gaye', year: 1968, previewUrl: '' },
  { title: 'Let\'s Get It On', artist: 'Marvin Gaye', year: 1973, previewUrl: '' },
  { title: 'Sexual Healing', artist: 'Marvin Gaye', year: 1982, previewUrl: '' },
  { title: 'Signed, Sealed, Delivered I\'m Yours', artist: 'Stevie Wonder', year: 1970, previewUrl: '' },
  { title: 'Isn\'t She Lovely', artist: 'Stevie Wonder', year: 1976, previewUrl: '' },
  { title: 'I Just Called to Say I Love You', artist: 'Stevie Wonder', year: 1984, previewUrl: '' },
  { title: 'Son of a Preacher Man', artist: 'Dusty Springfield', year: 1968, previewUrl: '' },
  { title: 'Build Me Up Buttercup', artist: 'The Foundations', year: 1968, previewUrl: '' },
  { title: 'Can\'t Take My Eyes Off You', artist: 'Frankie Valli', year: 1967, previewUrl: '' },
  { title: 'Oh, Pretty Woman', artist: 'Roy Orbison', year: 1964, previewUrl: '' },
  { title: 'Stand by Your Man', artist: 'Tammy Wynette', year: 1968, previewUrl: '' },
  { title: 'Ring of Fire', artist: 'Johnny Cash', year: 1963, previewUrl: '' },
  { title: 'I Walk the Line', artist: 'Johnny Cash', year: 1956, previewUrl: '' },
  { title: 'Folsom Prison Blues', artist: 'Johnny Cash', year: 1955, previewUrl: '' },
  { title: 'Hurt', artist: 'Johnny Cash', year: 2002, previewUrl: '' },
  { title: 'Jolene', artist: 'Dolly Parton', year: 1973, previewUrl: '' },
  { title: '9 to 5', artist: 'Dolly Parton', year: 1980, previewUrl: '' },
  { title: 'Country Roads', artist: 'John Denver', year: 1971, previewUrl: '' },
  { title: 'Sweet Caroline', artist: 'Neil Diamond', year: 1969, previewUrl: '' },
  { title: 'Piano Man', artist: 'Billy Joel', year: 1973, previewUrl: '' },
  { title: 'Uptown Girl', artist: 'Billy Joel', year: 1983, previewUrl: '' },
  { title: 'We Didn\'t Start the Fire', artist: 'Billy Joel', year: 1989, previewUrl: '' },
  { title: 'The River', artist: 'Bruce Springsteen', year: 1980, previewUrl: '' },
  { title: 'Dancing in the Dark', artist: 'Bruce Springsteen', year: 1984, previewUrl: '' },
  { title: 'Streets of Philadelphia', artist: 'Bruce Springsteen', year: 1993, previewUrl: '' },
  { title: 'Landslide', artist: 'Fleetwood Mac', year: 1975, previewUrl: '' },
  { title: 'The Chain', artist: 'Fleetwood Mac', year: 1977, previewUrl: '' },
  { title: 'Rhiannon', artist: 'Fleetwood Mac', year: 1975, previewUrl: '' },
  { title: 'Everybody Wants to Rule the World', artist: 'Tears for Fears', year: 1985, previewUrl: '' },
  { title: 'Shout', artist: 'Tears for Fears', year: 1984, previewUrl: '' },
  { title: 'Come on Eileen', artist: 'Dexys Midnight Runners', year: 1982, previewUrl: '' },
  { title: 'Every Little Thing She Does Is Magic', artist: 'The Police', year: 1981, previewUrl: '' },
  { title: 'Message in a Bottle', artist: 'The Police', year: 1979, previewUrl: '' },
  { title: 'Don\'t Stand So Close to Me', artist: 'The Police', year: 1980, previewUrl: '' },
  { title: 'In the Air Tonight', artist: 'Phil Collins', year: 1981, previewUrl: '' },
  { title: 'Against All Odds', artist: 'Phil Collins', year: 1984, previewUrl: '' },
  { title: 'Easy Lover', artist: 'Philip Bailey & Phil Collins', year: 1984, previewUrl: '' },
  { title: 'Born in the U.S.A.', artist: 'Bruce Springsteen', year: 1984, previewUrl: '' },
  { title: '99 Luftballons', artist: 'Nena', year: 1983, previewUrl: '' },
  { title: 'Safety Dance', artist: 'Men Without Hats', year: 1982, previewUrl: '' },
  { title: 'Owner of a Lonely Heart', artist: 'Yes', year: 1983, previewUrl: '' },
  { title: 'Kids in America', artist: 'Kim Wilde', year: 1981, previewUrl: '' },
  { title: 'Tempted', artist: 'Squeeze', year: 1981, previewUrl: '' },
  { title: 'Our House', artist: 'Madness', year: 1982, previewUrl: '' },
  { title: 'One Step Beyond', artist: 'Madness', year: 1979, previewUrl: '' },
  { title: 'Once in a Lifetime', artist: 'Talking Heads', year: 1980, previewUrl: '' },
  { title: 'Psycho Killer', artist: 'Talking Heads', year: 1977, previewUrl: '' },
  { title: 'Rock the Casbah', artist: 'The Clash', year: 1982, previewUrl: '' },
  { title: 'Should I Stay or Should I Go', artist: 'The Clash', year: 1982, previewUrl: '' },
  { title: 'London Calling', artist: 'The Clash', year: 1979, previewUrl: '' },
  { title: 'Blitzkrieg Bop', artist: 'Ramones', year: 1976, previewUrl: '' },
  { title: 'I Wanna Be Sedated', artist: 'Ramones', year: 1978, previewUrl: '' },
  { title: 'Anarchy in the U.K.', artist: 'Sex Pistols', year: 1976, previewUrl: '' },
  { title: 'Love Will Tear Us Apart', artist: 'Joy Division', year: 1980, previewUrl: '' },
  { title: 'Just Can\'t Get Enough', artist: 'Depeche Mode', year: 1981, previewUrl: '' },
  { title: 'Enjoy the Silence', artist: 'Depeche Mode', year: 1990, previewUrl: '' },
  { title: 'Personal Jesus', artist: 'Depeche Mode', year: 1989, previewUrl: '' },
  { title: 'This Charming Man', artist: 'The Smiths', year: 1983, previewUrl: '' },
  { title: 'There Is a Light That Never Goes Out', artist: 'The Smiths', year: 1986, previewUrl: '' },
  { title: 'Just Like Heaven', artist: 'The Cure', year: 1987, previewUrl: '' },
  { title: 'Friday I\'m in Love', artist: 'The Cure', year: 1992, previewUrl: '' },
  { title: 'Lovesong', artist: 'The Cure', year: 1989, previewUrl: '' },
  { title: 'Where Is My Mind?', artist: 'Pixies', year: 1988, previewUrl: '' },
  { title: 'Black', artist: 'Pearl Jam', year: 1991, previewUrl: '' },
  { title: 'Alive', artist: 'Pearl Jam', year: 1991, previewUrl: '' },
  { title: 'Man in the Box', artist: 'Alice in Chains', year: 1990, previewUrl: '' },
  { title: 'Black Hole Sun', artist: 'Soundgarden', year: 1994, previewUrl: '' },
  { title: 'Come As You Are', artist: 'Nirvana', year: 1991, previewUrl: '' },
  { title: 'Heart-Shaped Box', artist: 'Nirvana', year: 1993, previewUrl: '' },
  { title: 'About a Girl', artist: 'Nirvana', year: 1989, previewUrl: '' },
  { title: 'Everlong', artist: 'Foo Fighters', year: 1997, previewUrl: '' },
  { title: 'Learn to Fly', artist: 'Foo Fighters', year: 1999, previewUrl: '' },
  { title: 'Best of You', artist: 'Foo Fighters', year: 2005, previewUrl: '' },
  { title: 'Plush', artist: 'Stone Temple Pilots', year: 1992, previewUrl: '' },
  { title: 'Interstate Love Song', artist: 'Stone Temple Pilots', year: 1994, previewUrl: '' },
  { title: 'One', artist: 'U2', year: 1991, previewUrl: '' },
  { title: 'Where the Streets Have No Name', artist: 'U2', year: 1987, previewUrl: '' },
  { title: 'Sunday Bloody Sunday', artist: 'U2', year: 1983, previewUrl: '' },
  { title: 'Vertigo', artist: 'U2', year: 2004, previewUrl: '' },
  { title: 'Karma Police', artist: 'Radiohead', year: 1997, previewUrl: '' },
  { title: 'No Surprises', artist: 'Radiohead', year: 1997, previewUrl: '' },
  { title: 'Paranoid Android', artist: 'Radiohead', year: 1997, previewUrl: '' },
  { title: 'Yellow', artist: 'Coldplay', year: 2000, previewUrl: '' },
  { title: 'The Scientist', artist: 'Coldplay', year: 2002, previewUrl: '' },
  { title: 'Fix You', artist: 'Coldplay', year: 2005, previewUrl: '' },
  { title: 'Paradise', artist: 'Coldplay', year: 2011, previewUrl: '' },
  { title: 'A Sky Full of Stars', artist: 'Coldplay', year: 2014, previewUrl: '' },
  { title: 'Take Me Out', artist: 'Franz Ferdinand', year: 2004, previewUrl: '' },
  { title: 'Sex on Fire', artist: 'Kings of Leon', year: 2008, previewUrl: '' },
  { title: 'Chelsea Dagger', artist: 'The Fratellis', year: 2006, previewUrl: '' },
  { title: 'Fluorescent Adolescent', artist: 'Arctic Monkeys', year: 2007, previewUrl: '' },
  { title: 'I Bet You Look Good on the Dancefloor', artist: 'Arctic Monkeys', year: 2005, previewUrl: '' },
  { title: 'Do I Wanna Know?', artist: 'Arctic Monkeys', year: 2013, previewUrl: '' },
  { title: 'R U Mine?', artist: 'Arctic Monkeys', year: 2012, previewUrl: '' },
  { title: 'Naive', artist: 'The Kooks', year: 2006, previewUrl: '' },
  { title: 'She Moves in Her Own Way', artist: 'The Kooks', year: 2006, previewUrl: '' },
  { title: 'Valerie', artist: 'The Zutons', year: 2006, previewUrl: '' },
  { title: 'Dog Days Are Over', artist: 'Florence + the Machine', year: 2008, previewUrl: '' },
  { title: 'Shake It Out', artist: 'Florence + the Machine', year: 2011, previewUrl: '' },
  { title: 'I Bet You Look Good on the Dancefloor', artist: 'Arctic Monkeys', year: 2005, previewUrl: '' },
  { title: 'Electric Feel', artist: 'MGMT', year: 2007, previewUrl: '' },
  { title: 'Kids', artist: 'MGMT', year: 2008, previewUrl: '' },
  { title: 'Time to Pretend', artist: 'MGMT', year: 2007, previewUrl: '' },
  { title: 'Chocolate', artist: 'The 1975', year: 2013, previewUrl: '' },
  { title: 'Somebody Else', artist: 'The 1975', year: 2016, previewUrl: '' },
  { title: 'Young Folks', artist: 'Peter Bjorn and John', year: 2006, previewUrl: '' },
  { title: 'Float On', artist: 'Modest Mouse', year: 2004, previewUrl: '' },
  { title: 'Ho Hey', artist: 'The Lumineers', year: 2012, previewUrl: '' },
  { title: 'Little Talks', artist: 'Of Monsters and Men', year: 2011, previewUrl: '' },
  { title: 'Skinny Love', artist: 'Bon Iver', year: 2007, previewUrl: '' },
  { title: 'The Cave', artist: 'Mumford & Sons', year: 2009, previewUrl: '' },
  { title: 'I Will Wait', artist: 'Mumford & Sons', year: 2012, previewUrl: '' },
  { title: 'Little Lion Man', artist: 'Mumford & Sons', year: 2009, previewUrl: '' },
  { title: 'Pompeii', artist: 'Bastille', year: 2013, previewUrl: '' },
  { title: 'Riptide', artist: 'Vance Joy', year: 2013, previewUrl: '' },
  { title: 'Budapest', artist: 'George Ezra', year: 2013, previewUrl: '' },
  { title: 'Take Me to Church', artist: 'Hozier', year: 2013, previewUrl: '' },
  { title: 'Renegades', artist: 'X Ambassadors', year: 2015, previewUrl: '' },
  { title: 'Ain\'t It Fun', artist: 'Paramore', year: 2013, previewUrl: '' },
  { title: 'Misery Business', artist: 'Paramore', year: 2007, previewUrl: '' },
  { title: 'Decode', artist: 'Paramore', year: 2008, previewUrl: '' },
  { title: 'I Write Sins Not Tragedies', artist: 'Panic! at the Disco', year: 2006, previewUrl: '' },
  { title: 'High Hopes', artist: 'Panic! at the Disco', year: 2018, previewUrl: '' },
  { title: 'Sugar, We\'re Goin Down', artist: 'Fall Out Boy', year: 2005, previewUrl: '' },
  { title: 'Centuries', artist: 'Fall Out Boy', year: 2014, previewUrl: '' },
  { title: 'Thnks fr th Mmrs', artist: 'Fall Out Boy', year: 2007, previewUrl: '' },
  { title: 'Bohemian Like You', artist: 'The Dandy Warhols', year: 2000, previewUrl: '' },
  { title: 'Last Nite', artist: 'The Strokes', year: 2001, previewUrl: '' },
  { title: 'Reptilia', artist: 'The Strokes', year: 2003, previewUrl: '' },
  { title: 'Maps', artist: 'Yeah Yeah Yeahs', year: 2003, previewUrl: '' },
  { title: 'Heads Will Roll', artist: 'Yeah Yeah Yeahs', year: 2009, previewUrl: '' },
  { title: 'Feel Good Inc.', artist: 'Gorillaz', year: 2005, previewUrl: '' },
  { title: 'Clint Eastwood', artist: 'Gorillaz', year: 2001, previewUrl: '' },
  { title: 'On Melancholy Hill', artist: 'Gorillaz', year: 2010, previewUrl: '' },
  { title: 'Breezeblocks', artist: 'alt-J', year: 2012, previewUrl: '' },
  { title: 'Sweater Weather', artist: 'The Neighbourhood', year: 2012, previewUrl: '' },
  { title: 'Somebody to Love', artist: 'Queen', year: 1976, previewUrl: '' },
  { title: 'Killer Queen', artist: 'Queen', year: 1974, previewUrl: '' },
  { title: 'Fat Bottomed Girls', artist: 'Queen', year: 1978, previewUrl: '' },
  { title: 'Radio Ga Ga', artist: 'Queen', year: 1984, previewUrl: '' },
  { title: 'Valerie', artist: 'Amy Winehouse', year: 2007, previewUrl: '' },
  { title: 'Back to Black', artist: 'Amy Winehouse', year: 2006, previewUrl: '' },
  { title: 'Tears Dry on Their Own', artist: 'Amy Winehouse', year: 2007, previewUrl: '' },
  { title: 'Set Fire to the Third Bar', artist: 'Snow Patrol', year: 2006, previewUrl: '' },
  { title: 'Run', artist: 'Snow Patrol', year: 2003, previewUrl: '' },
  { title: 'Take Me to Church', artist: 'Hozier', year: 2013, previewUrl: '' },
  { title: 'Cheap Thrills', artist: 'Sia ft. Sean Paul', year: 2016, previewUrl: '' },
  { title: 'Elastic Heart', artist: 'Sia', year: 2015, previewUrl: '' },
  { title: 'Ex\'s & Oh\'s', artist: 'Elle King', year: 2014, previewUrl: '' },
  { title: 'Riptide', artist: 'Vance Joy', year: 2013, previewUrl: '' },
  { title: 'Demons', artist: 'Imagine Dragons', year: 2012, previewUrl: '' },
  { title: 'It\'s Time', artist: 'Imagine Dragons', year: 2011, previewUrl: '' },
  { title: 'Whatever It Takes', artist: 'Imagine Dragons', year: 2017, previewUrl: '' },
]